/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.ThiSinh;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Audd
 */
public class HoSoPanel extends javax.swing.JPanel {
    
    private String stateForm = "DEFAULT";

    /**
     * Creates new form HoSoPanel
     *
     * @throws java.sql.SQLException
     */
    public HoSoPanel() throws SQLException {
        initComponents();
        BUS.ThiSinhBUS.getAllThiSinhs(tblHoSo);
        eror1.setVisible(false);
        eror2.setVisible(false);
        eror3.setVisible(false);
        eror4.setVisible(false);
        eror5.setVisible(false);
        eror6.setVisible(false);
        eror7.setVisible(false);
        btnAccept.setVisible(false);
        btnDestroy.setVisible(false);
        btnClear.setVisible(false);
        txtID.setEnabled(false);
        enableComponent(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbbNgaySinh = new javax.swing.JComboBox<>();
        cbbThangSinh = new javax.swing.JComboBox<>();
        cbbNamSinh = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        rdoNam = new javax.swing.JRadioButton();
        rdoNu = new javax.swing.JRadioButton();
        cbbNoiSinh = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDienThoai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtSoBaoDanhTK = new javax.swing.JTextField();
        cbbGioiTinhTK = new javax.swing.JComboBox<>();
        cbbNoiSinhTK = new javax.swing.JComboBox<>();
        cbbUuTienTK = new javax.swing.JComboBox<>();
        rdoSBD = new javax.swing.JRadioButton();
        rdoTatCa = new javax.swing.JRadioButton();
        btnTimKiem = new javax.swing.JButton();
        btnLoad = new javax.swing.JButton();
        cbbUuTien = new javax.swing.JComboBox<>();
        btnDong = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        txtCmntd = new javax.swing.JTextField();
        eror1 = new javax.swing.JLabel();
        eror2 = new javax.swing.JLabel();
        eror3 = new javax.swing.JLabel();
        eror4 = new javax.swing.JLabel();
        eror5 = new javax.swing.JLabel();
        eror6 = new javax.swing.JLabel();
        eror7 = new javax.swing.JLabel();
        btnDestroy = new javax.swing.JButton();
        btnAccept = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoSo = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Họ Tên:");

        txtHoTen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ngày sinh:");

        cbbNgaySinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNgaySinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cbbThangSinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbThangSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));

        cbbNamSinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNamSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Giới Tính:");

        buttonGroup1.add(rdoNam);
        rdoNam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNam.setSelected(true);
        rdoNam.setText("Nam");
        rdoNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNamActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdoNu);
        rdoNu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoNu.setText("Nữ");
        rdoNu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoNuActionPerformed(evt);
            }
        });

        cbbNoiSinh.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNoiSinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hà Nội", "Hà Tây", "Hải Dương", "Bắc Ninh", "Hà Giang", "Hà Nam", "Lạng Sơn" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Nơi Sinh:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Địa Chỉ:");

        txtDiaChi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtSoDienThoai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Số Điện Thoại:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ưu Tiên:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel9.setText("Thông Tin Cá Nhân");

        btnThem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-check-mark-16.png"))); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-edit-16.png"))); // NOI18N
        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-delete-16.png"))); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-clear-symbol-16.png"))); // NOI18N
        btnClear.setText("Clear textbox");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel10.setText("Tìm Kiếm ");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Giới Tính:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Số Báo Danh:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Nơi Sinh:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Ưu Tiên:");

        txtSoBaoDanhTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        cbbGioiTinhTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbGioiTinhTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Tất Cả>", "Nam", "Nữ" }));

        cbbNoiSinhTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbNoiSinhTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Tất Cả>", "Hà Nội", "Hà Tây", "Hải Dương", "Bắc Ninh", "Hà Giang", "Hà Nam", "Lạng Sơn" }));

        cbbUuTienTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbUuTienTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Tất Cả>", "UT1", "UT2", "KV1", "KV2-NT", "KV2", "KV3" }));

        buttonGroup2.add(rdoSBD);
        rdoSBD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoSBD.setSelected(true);
        rdoSBD.setText("Tìm kiếm theo SBD");

        buttonGroup2.add(rdoTatCa);
        rdoTatCa.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rdoTatCa.setText("Tìm kiếm theo tiêu chí");

        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-16.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnLoad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnLoad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-refresh-16.png"))); // NOI18N
        btnLoad.setText("Refresh");
        btnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadActionPerformed(evt);
            }
        });

        cbbUuTien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbbUuTien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "UT1", "UT2", "KV1", "KV2-NT", "KV2", "KV3" }));

        btnDong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        jLabel15.setText("ID:");

        jLabel16.setText("CMTND:");

        txtCmntd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        eror1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror1.setForeground(new java.awt.Color(255, 0, 51));
        eror1.setText("Ko chứa kí tự đặc biệt");

        eror2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror2.setForeground(new java.awt.Color(255, 0, 51));
        eror2.setText("Chỉ chứa kí tự chữ");

        eror3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror3.setForeground(new java.awt.Color(255, 0, 51));
        eror3.setText("Ngày không tồn tại");

        eror4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror4.setForeground(new java.awt.Color(255, 0, 51));
        eror4.setText("Chỉ chứa số, ko trùng");

        eror5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror5.setForeground(new java.awt.Color(255, 0, 51));
        eror5.setText("Ko được để trống");

        eror6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror6.setForeground(new java.awt.Color(255, 0, 51));
        eror6.setText("Chỉ chứa số");

        eror7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror7.setForeground(new java.awt.Color(255, 0, 51));
        eror7.setText("Sai định dạng email");

        btnDestroy.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDestroy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-refresh-16.png"))); // NOI18N
        btnDestroy.setText("Bỏ qua");
        btnDestroy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDestroyActionPerformed(evt);
            }
        });

        btnAccept.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAccept.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-check-mark-16.png"))); // NOI18N
        btnAccept.setText("Chấp nhận");
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbbUuTien, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eror7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(eror6))))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rdoTatCa)
                                .addComponent(rdoSBD))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnLoad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jLabel10)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel11)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtSoBaoDanhTK)
                                .addComponent(cbbGioiTinhTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbNoiSinhTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cbbUuTienTK, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel15))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtID, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(txtHoTen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eror1)
                            .addComponent(eror2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel16))
                        .addGap(40, 40, 40)
                        .addComponent(cbbNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtCmntd, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(rdoNam)
                                            .addGap(14, 14, 14)
                                            .addComponent(rdoNu))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(cbbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbbThangSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cbbNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eror3)
                            .addComponent(eror4)
                            .addComponent(eror5)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnThem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnXoa))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAccept)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDestroy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDong))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbbNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbThangSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbbNamSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rdoNam)
                    .addComponent(rdoNu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbbNoiSinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtCmntd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(eror5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(eror6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(eror7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbUuTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDestroy)
                    .addComponent(btnAccept)
                    .addComponent(btnClear)
                    .addComponent(btnDong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtSoBaoDanhTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cbbGioiTinhTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cbbNoiSinhTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cbbUuTienTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoSBD)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdoTatCa)
                    .addComponent(btnLoad))
                .addContainerGap())
        );

        tblHoSo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tblHoSo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thí sinh", "Họ Tên", "Địa Chỉ", "Nơi Sinh", "CMTND", "Giới Tính", "Ngày Sinh", "Số Điện Thoại", "Email", "Ưu Tiên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoSo.getTableHeader().setReorderingAllowed(false);
        tblHoSo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoSoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoSo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tblHoSoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoSoMouseClicked
        
        DefaultTableModel model = (DefaultTableModel) tblHoSo.getModel();
        int selectedRow = tblHoSo.getSelectedRow();
        String[] ngaySinh = model.getValueAt(selectedRow, 6).toString().split("-");
        cbbNamSinh.getModel().setSelectedItem(ngaySinh[0]);
        cbbThangSinh.getModel().setSelectedItem(ngaySinh[1]);
        cbbNgaySinh.getModel().setSelectedItem(ngaySinh[2].substring(0, 2));
        String gioiTinh = model.getValueAt(selectedRow, 5).toString();
        if (gioiTinh.equals("Nam")) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        cbbNoiSinh.getModel().setSelectedItem(model.getValueAt(selectedRow, 3).toString());
        txtID.setText(model.getValueAt(selectedRow, 0).toString());
        txtHoTen.setText(model.getValueAt(selectedRow, 1).toString());
        txtCmntd.setText(model.getValueAt(selectedRow, 4).toString());
        txtDiaChi.setText(model.getValueAt(selectedRow, 2).toString());
        txtSoDienThoai.setText(model.getValueAt(selectedRow, 7).toString());
        txtEmail.setText(model.getValueAt(selectedRow, 8).toString());
        cbbUuTien.getModel().setSelectedItem(model.getValueAt(selectedRow, 9).toString());

    }//GEN-LAST:event_tblHoSoMouseClicked

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        HoSoPanel.this.getParent().remove(HoSoPanel.this);
        MainFormAdmin.check1 = 0;
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if (rdoSBD.isSelected()) {
            BUS.ThiSinhBUS.getThiSinh(tblHoSo, txtSoBaoDanhTK.getText(), this);
        } else {
            BUS.ThiSinhBUS.searchThiSinh(cbbGioiTinhTK, cbbNoiSinhTK, cbbUuTienTK, tblHoSo);
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        String id = txtID.getText();
        if(id == null || "".equals(id)){
             JOptionPane.showMessageDialog(this, "Mơi chọ thí sinh muốn xóa", "Thông Báo", JOptionPane.ERROR_MESSAGE);
             return;
        }
        String hoTen = txtHoTen.getText();
        String ngaySinh = cbbNamSinh.getSelectedItem().toString() + "-" + cbbThangSinh.getSelectedItem().toString() + "-" + cbbNgaySinh.getSelectedItem().toString();
        String gioiTinh;
        if (rdoNam.isSelected()) {
            gioiTinh = "Nam";
        } else {
            gioiTinh = "Nữ";
        }
        String noiSinh = cbbNoiSinh.getSelectedItem().toString();
        String diaChi = txtDiaChi.getText();
        String soDienThoai = txtSoDienThoai.getText();
        String email = txtEmail.getText();
        String uuTien = cbbUuTien.getSelectedItem().toString();
        String cmtnd = txtCmntd.getText();
        
        ThiSinh a = new ThiSinh(id, hoTen, noiSinh, cmtnd, diaChi, gioiTinh, ngaySinh, soDienThoai, email, uuTien);
        int dk = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn xóa không?", "Thông Báo", JOptionPane.OK_CANCEL_OPTION);
        if (dk == JOptionPane.OK_OPTION) {
            try {
                BUS.ThiSinhBUS.deleteThiSinh(a);
                BUS.ThiSinhBUS.getAllThiSinhs(tblHoSo);
                clearBox();
                JOptionPane.showMessageDialog(this, "Xóa thí sinh thành công!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

    }//GEN-LAST:event_btnXoaActionPerformed
    
    private void checkInputInfo(String id, String hoTen, JComboBox d, JComboBox m, JComboBox y, String cmtnd, String diaChi, String soDienThoai, String email) {
        if (!BUS.UtilityClass.validFullName(hoTen)) {
            eror2.setVisible(true);
        } else {
            eror2.setVisible(false);
        }
        if (BUS.UtilityClass.hasSpecChar(id) || id.equals("")) {
            eror1.setVisible(true);
        } else {
            eror1.setVisible(false);
        }
        if (!BUS.UtilityClass.validDate(d, m, y)) {
            eror3.setVisible(true);
        } else {
            eror3.setVisible(false);
        }
        if (BUS.UtilityClass.hasLetter(cmtnd) || BUS.UtilityClass.hasSpecChar(cmtnd) || cmtnd.length() < 9) {
            eror4.setVisible(true);
        } else {
            eror4.setVisible(false);
        }
        if (diaChi.equals("")) {
            eror5.setVisible(true);
        } else {
            eror5.setVisible(false);
        }
        if (!BUS.UtilityClass.validNumberPhone(soDienThoai)) {
            eror6.setVisible(true);
        } else {
            eror6.setVisible(false);
        }
        if (!BUS.UtilityClass.validEmail(email)) {
            eror7.setVisible(true);
        } else {
            eror7.setVisible(false);
        }
    }
    
    private void clearBox() {
        txtHoTen.setText("");
        txtCmntd.setText("");
        txtDiaChi.setText("");
        txtEmail.setText("");
        txtSoDienThoai.setText("");
    }

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        btnAccept.setVisible(true);
        btnDestroy.setVisible(true);
        enableComponent(true);
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        btnClear.setVisible(true);
        stateForm = "UPDATE";
        

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        btnAccept.setVisible(true);
        btnDestroy.setVisible(true);
        enableComponent(true);
        btnThem.setVisible(false);
        btnSua.setVisible(false);
        btnXoa.setVisible(false);
        btnClear.setVisible(true);
        stateForm = "ADD";
        clearBox();
        txtID.setText( BUS.ThiSinhBUS.getSeqThiSinh());
        tblHoSo.clearSelection();
    }//GEN-LAST:event_btnThemActionPerformed
    
    public void enableComponent(boolean bIs) {
        txtHoTen.setEnabled(bIs);
        cbbNgaySinh.setEnabled(bIs);
        cbbThangSinh.setEnabled(bIs);
        cbbNamSinh.setEnabled(bIs);
        rdoNam.setEnabled(bIs);
        rdoNu.setEnabled(bIs);
        cbbNoiSinh.setEnabled(bIs);
        txtCmntd.setEnabled(bIs);
        txtDiaChi.setEnabled(bIs);
        txtSoDienThoai.setEnabled(bIs);
        txtEmail.setEnabled(bIs);
        cbbUuTien.setEnabled(bIs);
    }

    private void rdoNuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNuActionPerformed

    private void btnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadActionPerformed
        try {
            BUS.ThiSinhBUS.getAllThiSinhs(tblHoSo);
        } catch (SQLException ex) {
            Logger.getLogger(HoSoPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnLoadActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        clearBox();
    }//GEN-LAST:event_btnClearActionPerformed

    private void rdoNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdoNamActionPerformed

    private void btnDestroyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDestroyActionPerformed
        if("ADD".equals(stateForm)){
            txtID.setText("");
        }
        stateForm = "DEFAULT";
        btnAccept.setVisible(false);
        btnDestroy.setVisible(false);
        btnThem.setVisible(true);
        btnSua.setVisible(true);
        btnXoa.setVisible(true);
        btnClear.setVisible(false);
        enableComponent(false);
    }//GEN-LAST:event_btnDestroyActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        if ("ADD".equals(stateForm)) {
            String id = txtID.getText();
            String hoTen = txtHoTen.getText();
            String ngaySinh = cbbNamSinh.getSelectedItem().toString() + "-" + cbbThangSinh.getSelectedItem().toString() + "-" + cbbNgaySinh.getSelectedItem().toString();
            String gioiTinh;
            if (rdoNam.isSelected()) {
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            String noiSinh = cbbNoiSinh.getSelectedItem().toString();
            String diaChi = txtDiaChi.getText();
            String soDienThoai = txtSoDienThoai.getText();
            String email = txtEmail.getText();
            String uuTien = cbbUuTien.getSelectedItem().toString();
            String cmtnd = txtCmntd.getText();
            checkInputInfo(id, hoTen, cbbNgaySinh, cbbThangSinh, cbbNamSinh, cmtnd, diaChi, soDienThoai, email);
            if (BUS.ThiSinhBUS.getAThiSinh(cmtnd) != null) {
                eror4.setVisible(true);
            } else {
                eror4.setVisible(false);
            }
            if (BUS.ThiSinhBUS.findById(id) != null) {
                JOptionPane.showMessageDialog(this, "Thí Sinh Đã Tồn Tại!", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            } else if (!(BUS.UtilityClass.hasSpecChar(id) || id.equals("")) && BUS.UtilityClass.validFullName(hoTen) && BUS.UtilityClass.validDate(cbbNgaySinh, cbbThangSinh, cbbNamSinh)
                    && !(BUS.UtilityClass.hasLetter(cmtnd) || BUS.UtilityClass.hasSpecChar(cmtnd) || cmtnd.length() < 9 || BUS.ThiSinhBUS.getAThiSinh(cmtnd) != null) && !diaChi.equals("")
                    && BUS.UtilityClass.validNumberPhone(soDienThoai) && BUS.UtilityClass.validEmail(email)) {
                ThiSinh a = new ThiSinh(id, hoTen, noiSinh, cmtnd, diaChi, gioiTinh, ngaySinh, soDienThoai, email, uuTien);
                try {
                    BUS.ThiSinhBUS.insertThiSinh(a);
                    BUS.ThiSinhBUS.getAllThiSinhs(tblHoSo);
                    clearBox();
                    JOptionPane.showMessageDialog(this, "Thêm Thí Sinh thành công!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                    stateForm = "DEFAULT";
                    btnAccept.setVisible(false);
                    btnDestroy.setVisible(false);
                    btnThem.setVisible(true);
                    btnSua.setVisible(true);
                    btnXoa.setVisible(true);
                    btnClear.setVisible(false);
                    enableComponent(false);
                } catch (SQLException ex) {
                    Logger.getLogger(HoSoPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else if ("UPDATE".equals(stateForm)) {
            String id = txtID.getText();
            String hoTen = txtHoTen.getText();
            String ngaySinh = cbbNamSinh.getSelectedItem().toString() + "-" + cbbThangSinh.getSelectedItem().toString() + "-" + cbbNgaySinh.getSelectedItem().toString();
            String gioiTinh;
            if (rdoNam.isSelected()) {
                gioiTinh = "Nam";
            } else {
                gioiTinh = "Nữ";
            }
            String noiSinh = cbbNoiSinh.getSelectedItem().toString();
            String diaChi = txtDiaChi.getText();
            String soDienThoai = txtSoDienThoai.getText();
            String email = txtEmail.getText();
            String uuTien = cbbUuTien.getSelectedItem().toString();
            String cmtnd = txtCmntd.getText();
            checkInputInfo(id, hoTen, cbbNgaySinh, cbbThangSinh, cbbNgaySinh, cmtnd, diaChi, soDienThoai, email);
            if (BUS.ThiSinhBUS.getAThiSinh(cmtnd) != null) {
                eror4.setVisible(true);
            } else {
                eror4.setVisible(false);
            }
            if (!(BUS.UtilityClass.hasSpecChar(id) || id.equals("")) && BUS.UtilityClass.validFullName(hoTen) && BUS.UtilityClass.validDate(cbbNgaySinh, cbbThangSinh, cbbNamSinh)
                    && !(BUS.UtilityClass.hasLetter(cmtnd) || BUS.UtilityClass.hasSpecChar(cmtnd) || cmtnd.length() == 0 || BUS.ThiSinhBUS.getAThiSinh(cmtnd) != null) && !diaChi.equals("")
                    && BUS.UtilityClass.validNumberPhone(soDienThoai) && BUS.UtilityClass.validEmail(email)) {
                try {
                    ThiSinh a = new ThiSinh(id, hoTen, noiSinh, cmtnd, diaChi, gioiTinh, ngaySinh, soDienThoai, email, uuTien);
                    BUS.ThiSinhBUS.updateThiSinh(a);
                    BUS.ThiSinhBUS.getAllThiSinhs(tblHoSo);
                    clearBox();
                    JOptionPane.showMessageDialog(this, "Sửa thí sinh thành công!", "Thông Báo", JOptionPane.WARNING_MESSAGE);
                    stateForm = "DEFAULT";
                    btnAccept.setVisible(false);
                    btnDestroy.setVisible(false);
                    btnThem.setVisible(true);
                    btnSua.setVisible(true);
                    btnXoa.setVisible(true);
                    btnClear.setVisible(false);
                    enableComponent(false);
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Sửa thí sinh thất bại!", "Thông Báo", JOptionPane.ERROR_MESSAGE);
                    Logger.getLogger(HoSoPanel.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Sửa thí sinh thất bại!", "Thông Báo", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDestroy;
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnLoad;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbbGioiTinhTK;
    private javax.swing.JComboBox<String> cbbNamSinh;
    private javax.swing.JComboBox<String> cbbNgaySinh;
    private javax.swing.JComboBox<String> cbbNoiSinh;
    private javax.swing.JComboBox<String> cbbNoiSinhTK;
    private javax.swing.JComboBox<String> cbbThangSinh;
    private javax.swing.JComboBox<String> cbbUuTien;
    private javax.swing.JComboBox<String> cbbUuTienTK;
    private javax.swing.JLabel eror1;
    private javax.swing.JLabel eror2;
    private javax.swing.JLabel eror3;
    private javax.swing.JLabel eror4;
    private javax.swing.JLabel eror5;
    private javax.swing.JLabel eror6;
    private javax.swing.JLabel eror7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JRadioButton rdoSBD;
    private javax.swing.JRadioButton rdoTatCa;
    private javax.swing.JTable tblHoSo;
    private javax.swing.JTextField txtCmntd;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtSoBaoDanhTK;
    private javax.swing.JTextField txtSoDienThoai;
    // End of variables declaration//GEN-END:variables
}
