/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import DTO.TaiKhoan;
import javax.swing.JOptionPane;

/**
 *
 * @author Audd
 */
public class MatKhauPanel extends javax.swing.JPanel {

    /**
     * Creates new form MatKhauPanel
     */
    public MatKhauPanel() {
        initComponents();
        eror1.setVisible(false);
        eror2.setVisible(false);
        eror3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOldPass = new javax.swing.JPasswordField();
        txtNewPass = new javax.swing.JPasswordField();
        txtAgainPass = new javax.swing.JPasswordField();
        btnXacNhan = new javax.swing.JButton();
        btnDong = new javax.swing.JButton();
        eror1 = new javax.swing.JLabel();
        eror2 = new javax.swing.JLabel();
        eror3 = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setText("Đổi Mật Khẩu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mật Khẩu Cũ:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mật Khẩu Mới:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Nhập Lại Mật Khẩu:");

        txtOldPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtNewPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        txtAgainPass.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnXacNhan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-check-mark-16.png"))); // NOI18N
        btnXacNhan.setText("Xác Nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnDong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-close-16.png"))); // NOI18N
        btnDong.setText("Đóng");
        btnDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongActionPerformed(evt);
            }
        });

        eror1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror1.setForeground(new java.awt.Color(255, 0, 0));
        eror1.setText("Sai Mật Khẩu!");

        eror2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror2.setForeground(new java.awt.Color(255, 0, 0));
        eror2.setText("Mật Khẩu phải dài 8 kí tự gồm chữ cái, chữ hoa, số và kí tự đặc biệt");

        eror3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eror3.setForeground(new java.awt.Color(255, 0, 0));
        eror3.setText("Mật khẩu không khớp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(btnXacNhan))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNewPass)
                                .addComponent(txtAgainPass)
                                .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDong))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(eror1)
                            .addComponent(eror2)
                            .addComponent(eror3)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtOldPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtAgainPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eror3))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhan)
                    .addComponent(btnDong))
                .addContainerGap(178, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongActionPerformed
        MatKhauPanel.this.getParent().remove(MatKhauPanel.this);
        MainFormUser.check1 = 0;
    }//GEN-LAST:event_btnDongActionPerformed

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        String oldPass = String.valueOf(txtOldPass.getPassword());
        String newPass = String.valueOf(txtNewPass.getPassword());
        String againPass = String.valueOf(txtAgainPass.getPassword());
        if (!oldPass.equals(BUS.TaiKhoanBUS.a.getPassWord())) {
            eror1.setVisible(true);
        } else {
            eror1.setVisible(false);
        }
        if (!BUS.UtilityClass.validPassword(newPass)){
            eror2.setVisible(true);
        } else {
            eror2.setVisible(false);
        }
        if (!againPass.equals(newPass)) {
            eror3.setVisible(true);
        } else if (oldPass.equals(BUS.TaiKhoanBUS.a.getPassWord()) && BUS.UtilityClass.validPassword(newPass)){
            eror3.setVisible(false);
            TaiKhoan b = new TaiKhoan();
            b.setUserName(BUS.TaiKhoanBUS.a.getUserName());
            b.setQuyenHan(BUS.TaiKhoanBUS.a.getQuyenHan());
            b.setPassWord(againPass);
            BUS.TaiKhoanBUS.updateTaiKhoan(b);
            JOptionPane.showMessageDialog(this, "Đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
            txtOldPass.setText("");
            txtNewPass.setText("");
            txtAgainPass.setText("");
        }    
    }//GEN-LAST:event_btnXacNhanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDong;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JLabel eror1;
    private javax.swing.JLabel eror2;
    private javax.swing.JLabel eror3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField txtAgainPass;
    private javax.swing.JPasswordField txtNewPass;
    private javax.swing.JPasswordField txtOldPass;
    // End of variables declaration//GEN-END:variables
}
